apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drone-monorepo.fullname" . }}
  labels:
    {{- include "drone-monorepo.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "drone-monorepo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "drone-monorepo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "drone-monorepo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mono
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: mono
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /healthz
              port: mono
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PYTHONBUFFERED
              value: "1"
            - name: LOG_LEVEL
              value: DEBUG
            - name: TOKEN_PATH
              value: {{ .Values.github_token_path }}
            - name: DEFAULT_PIPELINE_TYPE
              value: {{ default "kubernetes" .Values.default_pipeline_type }}
            - name: DEFAULT_PLATFORM
              value: {{ default "linux-amd64" .Values.default_platform }}
            {{- range $name, $value := .Values.extraEnv }}
            - name: {{ $name }}
              value: {{ $value }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}