apiVersion: v1
kind: Service
metadata:
  name: {{ include "drone-monorepo.fullname" . }}
  labels:
    {{- include "drone-monorepo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mono
      protocol: TCP
      name: mono
  selector:
    {{- include "drone-monorepo.selectorLabels" . | nindent 4 }}
